import Head from "next/head";

const Head2 = () => {
  return (
    <Head>
      <title>Crypto Pay - Crypto payments for telegram bots</title>

      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />

      <link rel="icon" href="/logo.jpeg" />
      <link rel="apple-touch-icon" href="/logo.jpeg" />

      <meta name="theme-color" content="#000000" />
      <meta name="description" content="Crypto payments for telegram bots" />
      <meta
        name="keywords"
        content="crypto, payments, telegram, bots, cryptobot"
      />
      <meta name="author" content="@CryptoBot" />
      <meta name="robots" content="index, follow" />
      <meta name="language" content="en" />

      <meta
        name="og:title"
        content="Crypto Pay - Crypto payments for telegram bots"
      />
      <meta name="og:description" content="Crypto payments for telegram bots" />
      <meta
        name="og:image"
        content="https://cryptopay.vercel.app/og-image.png"
      />
      <meta name="og:url" content="https://cryptopay.vercel.app" />
      <meta name="og:site_name" content="Crypto Pay" />
      <meta name="og:locale" content="en_US" />
    </Head>
  );
};

export default Head2;
