name: Build Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm i

    - name: Build the app
      run: npm run build

    - name: Move build to build folder
      run: |
        mkdir -p build
        mv .next/* build/

    - name: Commit and push build folder
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add build/
        git commit -m "Add build folder" || echo "No changes to commit"
        git push https://ddddanya:${{ secrets.GH_PAT }}@github.com/ddddanya/cryptobot-contest.git
